# Generated by Django 3.2.7 on 2021-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address',
            new_name='street_address1',
        ),
        migrations.AddField(
            model_name='order',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
