# Generated by Django 3.2.7 on 2021-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='intensity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
