# Generated by Django 3.2.7 on 2021-10-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_size_price_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Size_Price',
            new_name='ProductSizePrice',
        ),
    ]
