# Generated by Django 3.2.7 on 2021-10-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_size_price_productsizeprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.DeleteModel(
            name='ProductSizePrice',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
